### ISSUE TITLE
What do these parameters mean?

### ISSUE THREAD

**Issue by adimehrotra** [mathworks/Simscape-Battery-Electric-Vehicle-Model#10]
Hi! Not an issue but a question, I'm trying to modify the R2022a version of this script to work for a vehicle I'm modeling. 

In BEV_params.m in the BEV folder, can someone please explain what roadLoad is?

![image](https://github.com/mathworks/Simscape-Battery-Electric-Vehicle-Model/assets/46380543/44552d8d-e748-434d-80d2-fd02aa6982fc)

**Comment by adimehrotra** [comment]
My guess is:

roadLoad A_N -->rolling resistance of some sort
C_N is a scaled coefficient of drag 

But I just wanted to confirm

**Comment by Isaac-Ito-MW** [comment]
They are the block parameters of Longitudinal Vehicle block. Please see the Parameters section of the documentation about the block:
https://www.mathworks.com/help/sdl/ref/longitudinalvehicle.html
