### ISSUE TITLE
I'd like to receive the parameter "PmsmFem"

### ISSUE THREAD

**Issue by OnYouPark** [mathworks/Simscape-Battery-Electric-Vehicle-Model#12]
Now I am trying to apply the FEM_PMSM motor model in the model to the basic model. However, unlike other parameters, the parameters of "PmsmFem" are not given in the model. You did a test to follow the motor torque in the model, can I get the parameters you used?

**Comment by Isaac-Ito-MW** [comment]
Hi, I posted answer at MATLAB Central File Exchange. FYI, I copy it here:

> Hi, you are right that parameters for the FEM-Parameterized PMSM block are not in the BEV system model parameters file. The FEM-Parameterized PMSM block is used to obtain electrical loss parameters for the Motor & Drive (System Level) block. Then the Motor & Drive (System Level) block is used in the BEV model.
> For the workflow to get Motor & Drive loss parameters from the FEM-Parameterized PMSM block, please see the "MotorDrive_calcElectricEfficiency.mlx" Live Script in DetailedModelApplications > MotorDrivePmsmsFEM.

And here is the link to the thread in File Exchange:

- https://www.mathworks.com/matlabcentral/fileexchange/82250-battery-electric-vehicle-model-in-simscape?tab=discussions#discussions_2524122

I'll close this topic. If you have further questions, please feel free to ask.
