### ISSUE TITLE
Failed to load sdl_lib, 5 times on loading BEV_System_Model

### ISSUE THREAD

**Issue by msw4chl** [mathworks/Simscape-Battery-Electric-Vehicle-Model#19]
After setup succeeded and clicking on BEV_System_Model in the App Explorer.

After 10-15 sec, I get the Simulink BEV System Model opens up, 

But then I get 5 different places this sdl_lib fails to learn. Where is this sdl_lib and how can I add it to the runtime?

Error:Failed to load library 'sdl_lib' referenced by 'BEV_system_model/Longitudinal Vehicle/Longitudinal Vehicle'.

Thanks for any tips!

PS - this is on Matlab Cloud with license for the Powertrain Block

**Comment by Isaac-Ito-MW** [comment]
`sdl_lib` is Simscape Driveline. The license for it is required to open the model.
