### ISSUE TITLE
Data about motor efficiency, maximum charging current vs state of charge

### ISSUE THREAD

**Issue by hesuieins** [mathworks/Simscape-Battery-Electric-Vehicle-Model#8]
Hi, I'm wondering if I could get the motor efficiency map and maximum charging current vs SOC of the model used?

**Comment by Isaac-Ito-MW** [comment]
Version 2.0.0 has an update in Motor Drive Unit component which includes information about motor efficiency map.

Maximum charging current vs SOC is not considered in the current project.
